### ISSUE TITLE
Watchcat erroring while attempting to pull new data from servers

### ISSUE THREAD

**Issue by HarryRybacki-zz** [sshnaidm/sova#7]
### Steps to recreate
1. Clone repo
2. Install requirements
3. Copy ssh key to root of project
4. python app.py
### Expected Outcome
1. Script runs, saves data to /tmp/ directory, and outputs contents to index template
### Actual Outcome
1. Script runs and then bawks

```
2016-06-06 10:06:16,741 - watchcat - DEBUG - GET http://logs.openstack.org/periodic/periodic-tripleo-ci-f22-ha-liberty/518174c/console.html.gz with ignore404=False
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    main()
  File "app.py", line 5, in main
    create_html()
  File "/home/hrybacki/git/sova/tripleoci/page.py", line 41, in create_html
    periodic=True)
  File "/home/hrybacki/git/sova/tripleoci/watchcat.py", line 67, in meow
    periodic=periodic
  File "/home/hrybacki/git/sova/tripleoci/filters.py", line 37, in __init__
    self.data = sorted(data, key=lambda i: i.ts, reverse=True)
  File "/home/hrybacki/git/sova/tripleoci/watchcat.py", line 57, in <genexpr>
    url, down_path=down_path, limit=limit).jobs)
  File "/home/hrybacki/git/sova/tripleoci/periodic.py", line 125, in get_jobs
    raw = self._get_more_data(j)
  File "/home/hrybacki/git/sova/tripleoci/periodic.py", line 101, in _get_more_data
    line = line.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 38: ordinal not in range(128)
```

**Comment by sshnaidm** [comment]
@HarryRybacki , is it still reproducible?

**Comment by sshnaidm** [comment]
Fixed
